# Массивы numpy

Основным объектом NumPy является однородный многомерный массив.ЭтоТаблица элементов (обычно чисел), все одного типа, индексируется как кортеж натуральных чисел.

Например, координаты точки в 3D пространстве\[1, 2, 1\] Имеет одна ось.Эта ось имеет 3 элемента, поэтому мы говорим, что она имеет длину из 3.В приведенном ниже примере массив имеет 2 оси. Первая ось имеет длину 2, вторая ось имеет длину 3.

In [ ]:
[[ 1., 0., 0.],
 [ 0., 1., 2.]]

Класс массива NumPy называется ndarray. Он также известен под псевдонимом array. Заметить что numpy.array не то же самое, что и стандарт Класса библиотеки Pythonarray.array, который обрабатывает только одномерныемассивы и предложения меньшей функциональности.Более важные атрибуты ndarray объект

ndarray.ndim
    количество осей (размеров) массива.
ndarray.shape
    размеры массива.Это кортеж целых чисел, указывающихРазмер массива в каждом измерении.Для матрицы ссеверный грядкиим столбцыshape будет(n,m). Длинаshape кортеж поэтому количество осейndim.
ndarray.size
    общее количество элементов массива.Это равнопроизведение элементовshape.
ndarray.dtype
    объект, описывающий Тип элементов в массиве.Можносоздайте или укажите dtype, используя стандартные типы Python.Кроме тогоNumPy предоставляет свои собственные типы.numpy.int32, numpy.int16, иnumpy.float64-это несколько примеров.
ndarray.itemsize
    размер в байтах каждого элемента массива.Например,массив элементов типаfloat64 Имеетitemsize 8 (=64/8), пока один из типаcomplex32 Имеетitemsize 4 (=32/8). этоэквивалентныйndarray.dtype.itemsize.
ndarray.data
    буфер, содержащий фактические элементы массива.Нормально, мыне нужно будет использовать этот атрибут, потому что мы будем обращаться к элементамв массиве с использованием средств индексирования.

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
type(a)
b = np.array([6, 7, 8])
print(b)
print(type(b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
[6 7 8]
<class 'numpy.ndarray'>


Библиотека включает в себя справочную документацию
На веб-сайте: http://docs.scipy.org

Интерактивная помощь:
(попробуйте запустить код ниже, не забудьте импортировать библиотеку)

In [ ]:
np.array?

In [ ]:
np.lookfor('create array') 

In [3]:
np.con*?

### Создание массивов
Ручное построение массивов

In [ ]:
# 1D
a = np.array([0, 1, 2, 3])
print(a)
# 2D
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)
# 3D
c = np.array([[[1], [2]], [[3], [4]]])
print(c)

Функции для создания массивов

In [8]:
# Равномерно
print("Равномерно")
a = np.arange(10)
print(a)
b = np.arange(1, 9, 2) # start, end (exclusive), step
print(b)
# или по количеству точек
c = np.linspace(0, 1, 6) # start, end, num-points
print(c)
d = np.linspace(0, 1, 5, endpoint=False)
print(d)
# Общие массивы
print("Общие массивы")
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
print(a)
b = np.zeros((2, 2))
print(b)
c = np.eye(3)
print(c)
d = np.diag(np.array([1, 2, 3, 4]))
print(d)
# Random
print("Random")
a = np.random.rand(4)       # uniform in 0, 1
print(a)
b = np.random.randn(4)      # Gaussian
print(b)


np.random.seed(1234))       # Setting the random seed

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[0.  0.2 0.4 0.6 0.8 1. ]
[0.  0.2 0.4 0.6 0.8]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[0.19151945 0.62210877 0.43772774 0.78535858]
[-0.72058873  0.88716294  0.85958841 -0.6365235 ]
None


### Основные типы данных
Вы, возможно, заметили, что в некоторых случаях элементы массива отображаются с конечные точки (например, 2. против 2). Это связано с разницей в используемый тип данных

In [9]:
a = np.array([1, 2, 3])
print(a.dtype)
b = np.array([1., 2., 3.])
print(b.dtype)

int32
float64


Различные типы данных позволяют более компактно хранить данные в памяти, но большую часть времени мы просто работаем с числами с плавающей точкой.Обратите внимание, что в приведенном выше примере NumPy автоматически определяет тип данных от входа.

Можно явно указать, какой тип данных требуется

In [10]:
c = np.array([1, 2, 3], dtype=float)
print(c.dtype)
# По умолчанию тип данных-плавающая точка
a = np.ones((3, 3))
print(a.dtype)

float64
float64


Есть и другие типы

Тип|Код
---|---
Комплекс|d = np.array(\[1+2j, 3+4j, 5+6*1j\])
Тип bool|e = np.array(\[True, False, False, True\])
Строки|f = np.array(\['Bonjour', 'Hello', 'Hallo'\])	
Другие|	int32,int64,uint32,uint64

### Базовая визуализация
(о matplotlib конкретнее мы поговорим позже)
Теперь, когда у нас есть первые массивы данных, мы их визуализируем.
Матплотлиб представляет собой пакет 2D-построения.Мы можем импортировать свои функции

In [32]:
import matplotlib.pyplot as plt
plt.plot(x, y)       # line plot
plt.show()           # <-- shows the plot (not needed with interactive plots
x = np.linspace(0, 3, 20)
y = np.linspace(0, 9, 20)
plt.plot(x, y)       # line plot

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
image = np.random.rand(30, 30)
plt.imshow(image, cmap=plt.cm.hot)    
plt.colorbar() 

### Индексирование и нарезка
Элементы массива могут быть доступны и назначены так же, как другие последовательности Python (например, списки)

In [ ]:
a = np.arange(10)
print(a[0], a[2], a[-1])
print(a[::-1])
print(a[2:9:3])
# Для многомерных массивов индексы являются кортежами целых чисел
a = np.diag(np.arange(3))
print(a)
print(a[1, 1])
print(a[1])

![title](https://www.scipy-lectures.org/_images/numpy_indexing.png)


In [12]:
a = np.arange(10)
a[5:] = 10
print(a)

b = np.arange(5)
a[5:] = b[::-1]
print(a)

[ 0  1  2  3  4 10 10 10 10 10]
[0 1 2 3 4 4 3 2 1 0]


### Копии и вид
Срезы создают вид на исходный массив, который дает доступ к данным массива. Таким образом, исходный массив не является скопированым в память. Вы можете использовать np.may_share_memory() , чтобы проверить.

In [15]:
a = np.arange(10)
print(a)
b = a[::2]
print(b)
np.may_share_memory(a, b)
b[0] = 12
print(b)
print(a) # !!!! a поменяет значение ВНИМАТЕЛЬНО

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[12  2  4  6  8]
[12  1  2  3  4  5  6  7  8  9]


In [13]:
a = np.arange(10)
c = a[::2].copy()  # force a copy
c[0] = 12
print(a)
np.may_share_memory(a, c)

[0 1 2 3 4 5 6 7 8 9]


False

### Необычные индексации
Массивы NumPy можно индексировать с помощью срезов, но также с логическими или целочисленными массивами. Этот метод называется необычные индексации. Он создает копию, а не вид.

In [18]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
print(a)
(a % 3 == 0)
mask = (a % 3 == 0)
extract_from_a = a[mask] # or, a[a%3==0
print(extract_from_a)           # extract a sub-array with the mask
a[a % 3 == 0] = -1
print(a)
print(extract_from_a) # Как видите extract_from_a не изменился

[10  3  8  0 19 10 11  9 10  6  0 20 12  7 14]
[ 3  0  9  6  0 12]
[10 -1  8 -1 19 10 11 -1 10 -1 -1 20 -1  7 14]
[ 3  0  9  6  0 12]


In [20]:
# Индексирование массивом целых чисел
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
idx.shape
print(a[idx])

[[3 4]
 [9 7]]


### Численные операции над массивами
#### Поэлементные операции

In [23]:
# Со скалярами
print("Со скалярами")
a = np.array([1, 2, 3, 4])
print(a + 1)
print(2**a)
# Вся арифметика
print("Вся арифметика")
b = np.ones(4) + 1
print(a - b)
print(a * b)
j = np.arange(5)
print(2**(j + 1) - j)
# Сравнения
print("Сравнения")
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(a == b)
print(a > b)
# Сравнение по массивам
print("Сравнение по массивам")
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])
print(np.array_equal(a, b))
print(np.array_equal(a, c))
# Логическая операция
print("Логическая операция")
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
print(np.logical_or(a, b))
print(np.logical_and(a, b))
# Трансцендентная функция
print("Трансцендентная функция")
a = np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))
# Несоответствия формы
print("Несоответствия формы")
a = np.arange(4)
print(a + np.array([1, 2])) 
# Перенос
print("Перенос")
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu
print(a)
print(a.T)
# 

[2 3 4 5]
[ 2  4  8 16]
[-1.  0.  1.  2.]
[2. 4. 6. 8.]
[ 2  3  6 13 28]
[False  True False  True]
[False False  True False]
False
True


### Основные сокращения

In [28]:
# Вычислительные суммы
print("Вычислительные суммы")
x = np.array([1, 2, 3, 4])
print(np.sum(x))
print(x.sum())
# Сумма по строкам и столбцам
print("Сумма по строкам и столбцам")
x = np.array([[1, 1], [2, 2]])
print(x)
print(x.sum(axis=0))   # columns (first dimension
print(x[:, 0].sum(), x[:, 1].sum())
print(x.sum(axis=1))   # rows (second dimension
print(x[0, :].sum(), x[1, :].sum())
# Экстремум
print("Экстремум")
x = np.array([1, 3, 2])
print(x.min())
print(x.max())
print(x.argmin())  # index of minimum
print(x.argmax())  # index of maximum
# Логическая операция
print("Логическая операция")
print(np.all([True, True, False]))
print(np.any([True, True, False]))
# Статистика
print("Статистика")
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
print(x.mean())
print(np.median(x))
print(np.median(y, axis=-1)) # last axis
print(x.std())         # full population standard dev.

Вычислительные суммы
10
10
Сумма по строкам и столбцам
[[1 1]
 [2 2]]
[3 3]
3 3
[2 4]
2 4
Экстремум
1
3
0
1
Логическая операция
False
True
Статистика
1.75
1.5
[2. 5.]
0.82915619758885


### Broadcasting
(Вещание, но перевод не отражает всей сути операции)
Это основные операции на массивами, работает с массивами одинакового размера.
Тем не менее, это также можно сделать над массивами различной размеры если и NumPy может превратить эти массивы так, что все они имеют одинаковый размер: это преобразование называется вещанием.
На рисунке ниже приведен пример вещания
![title](https://www.scipy-lectures.org/_images/numpy_broadcasting.png)

In [29]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
print(a)
b = np.array([0, 1, 2])
print(a + b)
# Полезный трюк
print("трюк")
a = np.arange(0, 40, 10)
print(a.shape)
a = a[:, np.newaxis]  # adds a new axis -> 2D array
print(a.shape)
print(a)
print(a + b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
трюк
(4,)
(4, 1)
[[ 0]
 [10]
 [20]
 [30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


Также можно использовать множество проблем на основе сетки или сети радиовещания.Например, если мы хотим вычислить расстояние от начало координат точек на сетке 10x10, мы можем сделать так:

In [30]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

In [31]:
# В цвете
plt.pcolor(distance)    
plt.colorbar() 

NameError: name 'plt' is not defined

Замечание: numpy.ogrid() функция позволяет непосредственно создавать векторы x и y из предыдущего примера, с двумя значительными измерениями

In [34]:
x, y = np.ogrid[0:5, 0:5]
print(x, y)
print(x.shape, y.shape)
distance = np.sqrt(x ** 2 + y ** 2)
print(distance)

[[0]
 [1]
 [2]
 [3]
 [4]] [[0 1 2 3 4]]
(5, 1) (1, 5)
[[0.         1.         2.         3.         4.        ]
 [1.         1.41421356 2.23606798 3.16227766 4.12310563]
 [2.         2.23606798 2.82842712 3.60555128 4.47213595]
 [3.         3.16227766 3.60555128 4.24264069 5.        ]
 [4.         4.12310563 4.47213595 5.         5.65685425]]


### Манипуляция формой массива

In [37]:
# Уплощение
print("Уплощение")
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel())
print(a.T)
print(a.T.ravel())
# Переформирование (обратное от уплощение)
print("Переформирование")
print(a.shape)
b = a.ravel()
b = b.reshape((2, 3))
print(b)
print(a.reshape((2, -1))) # unspecified (-1) value is inferred
# Добавление измерения
print("Добавление измерения")
z = np.array([1, 2, 3])
print(z)
print(z[:, np.newaxis])
print(z[np.newaxis, :])
# Перебирание измерений
print("Перебирание измерений")
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a.shape)
print(a[0, 2, 1])
b = a.transpose(1, 2, 0)
print(b.shape)
print(b[2, 1, 0])
# Изменение размера
print("Изменение размера")
a = np.arange(4)
print(a.resize((8,)))
print(a)
# но при изменении размера, массив не должен упоминаться где то еще
# b = a
# a.resize((4,)) # произойдет ошибка

Уплощение
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]
Переформирование
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
Добавление измерения
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]]
Перебирание измерений
(4, 3, 2)
5
(3, 2, 4)
5
Изменение размера
None
[0 1 2 3 0 0 0 0]


ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

### Сортировка данных

In [38]:
# Сортировка по оси
print("Сортировка по оси")
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
print(b)
# Сортировка на месте
print("Сортировка на месте")
a.sort(axis=1)
print(a)
# Сортировка с индексированием
print("Сортировка с индексированием")
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print(j)
print(a[j])
# Поиск минимумов и максимумов
print("Поиск минимумов и максимумов")
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
print(j_max, j_min)

Сортировка по оси
[[3 4 5]
 [1 1 2]]
Сортировка на месте
[[3 4 5]
 [1 1 2]]
Сортировка с индексированием
[2 3 1 0]
[1 2 3 4]
Поиск минимумов и максимумов
0 2


## Дополнительные операции
### Полиномы
NumPy также содержит полиномы в различных базах
(о полиномах в numpy http://docs.scipy.org/doc/numpy/reference/routines.polynomials.poly1d.html )

In [ ]:
p = np.poly1d([3, 2, -1])
print(p(0))
print(p.roots)
print(p.order)

In [ ]:
x = np.linspace(0, 1, 20)
y = np.cos(x) + 0.3*np.random.rand(20)
p = np.poly1d(np.polyfit(x, y, 3))
t = np.linspace(0, 1, 200)
plt.plot(x, y, 'o', t, p(t), '-')   

NumPy также имеет более сложный полиномиальный интерфейс, который поддерживает например, основа Чебышева.

In [ ]:
p = np.polynomial.Polynomial([-1, 2, 3]) # coefs in different order!
print(p(0))
print(p.roots())
print(p.degree())

In [ ]:
x = np.linspace(-1, 1, 2000)
y = np.cos(x) + 0.3*np.random.rand(2000)
p = np.polynomial.Chebyshev.fit(x, y, 90)
t = np.linspace(-1, 1, 200)
plt.plot(x, y, 'r.')   
plt.plot(t, p(t), 'k-', lw=3)   

### Загрузка файлов данных

In [ ]:
# Текстовый файл
# data = np.loadtxt('data/populations.txt')
# np.savetxt('pop2.txt', data)
# data2 = np.loadtxt('pop2.txt')

# Изображение
# img = plt.imread('data/elephant.png')
# img.shape, img.dtype
# plt.imshow(img)     
# plt.savefig('plot.png')
# plt.imsave('red_elephant.png', img[:,:,0], cmap=plt.cm.gray)